### ISSUE TITLE
How to Edit Widgets?

### ISSUE THREAD

**Issue by zerox1212** [FreeOpcUa/opcua-widgets#1]
I want to work on the NewMethod Widget, but there are no .ui files in this repository.

How do you edit the widgets with out a QT .ui file? Can you give me a quick overview of how to set up QT Designer so I can work on modeler and have access to the widgets?

Sorry in advance, I have only used QT a few times.

**Comment by oroulet** [comment]
no ui. Everything is written in code. This is more flexible. I do not want to discourage you but writting UI for methods will be quite hard. It will require to add widgets dynamically. so better start with something easier. Do you the UI btw? does it work?

**Comment by zerox1212** [comment]
You mean did I use the Method UI?

It adds a broken method. The arguments don't have 0:Argument as data type, and value is wrong. Clicking in the attributes fields crashes modeler.

Writing ui from code isn't totally new to me. I've done it in Android and iOS.

**Comment by oroulet** [comment]
so you can try fixing that first :-)

**Comment by zerox1212** [comment]
I will first just try to make the button create the method object properly. I don't know what you have in mind for UI.

**Comment by oroulet** [comment]
Feel free to propose something, but somewhere we need a list view widget where we can dynamically  add or remove  new arguments, with arbitraty name and docstring and of  any supported type. not very hard but requires some qt knowledge
Another important thing to do is add tests. at least in python-opcua for export and import/reexport of xml.
